name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: dist
          build_dir: dist
          commit_message: Deploy to Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
